remember_window_size no
initial_window_width 800
initial_window_height 640

background #12141e
background_opacity 0.9
background_blur 64
window_padding_width 10

font_family Inconsolata Nerd Font
font_size 16

cursor_trail 1
cursor_trail_decay 0.1 0.3
