if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

. "$HOME/.cargo/env" 

# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

alias xi="sudo xbps-install"
alias xs="sudo xbps-query -Rs"
alias xrm="sudo xbps-remove -R"

export EDITOR="nvim"

export PATH="\
$HOME/.local/bin:\
$HOME/.npm-global/bin:\
$HOME/go/bin:\
$PATH"
