if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

. $HOME/.cargo/env
. $HOME/.deno/env

export PATH="\
$HOME/.local/bin:\
$HOME/go/bin:\
$HOME/.local/share/pnpm/bin:\
$HOME/.config/composer/vendor/bin:\
/opt/flutter/bin:\
$PATH
"

alias xi="sudo xbps-install"
alias xrm="sudo xbps-remove -R"
alias xs="sudo xbps-query -Rs"
eval "$(direnv hook zsh)"
